### PR TITLE
Added some style with Bootstrap to the configuration

### LINKED ISSUE #3: Settings form redisign
Setting should look more intuitive and maybe shouldn't be displayed all the time.
Some modal or kind of a tab would probably be better here. Or maybe leaving it as it is, but just changing the look would help

### PR DESCRIPTION
**Pull request by AlanAlberino**
Tried to solve the issue of styling the configuration with Bootstrap. Hope you like it. 
Closes #3

### CODE REVIEW

**Comment by KonradLinkowski** [comment]
@AlanAlberino I think that adding bootstrap for such a small website is an overkill

**Review by KonradLinkowski — CHANGES_REQUESTED** [review]
Try mimic the bootstrap without bootstrap

**Comment by AlanAlberino** [comment]
> Try mimic the bootstrap without bootstrap

Ok, just made it, please check my new commit.

**Comment by KonradLinkowski** [comment]
Looks cool, just remove the package-lock.json from the commit if you can

**Comment by AlanAlberino** [comment]
> Looks cool, just remove the package-lock.json from the commit if you can

Sorry for that, just removed it in the 3rd. commit.

**Review by KonradLinkowski — APPROVED** [review]

**Comment by AlanAlberino** [comment]
Thanks for accepting the pull request, happy you liked it. Could you please add the "hacktoberfest-accepted" tag to it?

**Comment by KonradLinkowski** [comment]
@AlanAlberino I can add it but it doesn't change anything

**Comment by AlanAlberino** [comment]
> @AlanAlberino I can add it but it doesn't change anything

The merged pull request didn't count for my hacktoberfest participation, don't know why. Maybe adding the label it works, if you can help me with that it would be great :)

**Comment by KonradLinkowski** [comment]
Status of my PRs doesn't change as well, but I doubt that this is because the lack of a label.
I've read that thousands of people are spamming low quality PRs around the GitHub so the servers are overloaded.
Hacktoberfest servers probably are too overloaded too. Just be patient

**Comment by KonradLinkowski** [comment]
@AlanAlberino you were right. The label change things, but you didn't mention the information [source](https://hacktoberfest.digitalocean.com/hacktoberfest-update).
I now added this repo to the hacktoberfest topic and merged the PR, so it should count. If it's not counted let me know.

**Pull request merged**
